### ISSUE TITLE
what are the available types in cell_annotation.safelist_celltypes?

### ISSUE THREAD

**Issue by biopzhang** [Genentech/scimilarity#20]
Dear developers,

Thank you for the amazing tool! I'm trying to test the cell type annotation function on my own data. However, I got like 40+ cell types, among them some are redundant. In general, how do I use the safelist_celltypes feature?

I can think of two ways:
1. run annotation first, then select a sub-list from the resulted cell types, and rerun annotation;
2. predefine a list of cell types and run the annotation.

I tend to go with the second one, however, what are the available cell types there? 

Thank you so much!
Pengzhi

**Comment by javh** [comment]
Greetings @biopzhang ,

I usually do the first, but the downside is that it does restrict the available annotations to the 81 cell types in the curated default safelist.

For the the second approach, the full list of annotations used in training can be found on sheet **d.** (Training labels) of [Supplementary Table 1](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-024-08411-y/MediaObjects/41586_2024_8411_MOESM3_ESM.xlsx) and you can use any of those terms in a safelist. 

For reference, the curated default safelist can also be found in that same Excel file on sheet **e.** (Overall safelist). We should probably add these to either the docs site for the API or the Zenodo record for the model...

**Comment by biopzhang** [comment]
Hello @javh,

Thank you for the suggestion!

@tony-kuo Perfect! Thank you so much for the information. 

Pengzhi
