### ISSUE TITLE
Cell type annotations

### ISSUE THREAD

**Issue by sbg15236** [Genentech/scimilarity#25]
Not and issue, just a question because I couldn't find it...how can I get a list of the possible cell type annotations so that I can curate specific lists for my samples?
Thanks!

**Comment by javh** [comment]
Greetings @sbg15236,

The full list of annotations used in training can be found on sheet **d.** (Training labels) of [Supplementary Table 1](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-024-08411-y/MediaObjects/41586_2024_8411_MOESM3_ESM.xlsx). You can use any of those terms for annotation.

You can also find the list in the `CellAnnotation` class:

```
ca = CellAnnotation(model_path)
print(ca.classes)
```

For reference, the curated default safelist can also be found in that same Excel file on sheet **e.** (Overall safelist).

**Comment by sbg15236** [comment]
Thanks!
