### ISSUE TITLE
Unstated Input Data Formats

### ISSUE THREAD

**Issue by DarioS** [Genentech/scimilarity#3]
I see that the tutorial uses a h5ad format file. What are all of the input file formats which are supported? This is unstated.

**Comment by OmarSalem12** [comment]
Hi @DarioS, the `h5ad` is a common format to store scRNAseq experiments in the python ecosystem. Loading and saving the data is not a direct functionality of SCimilarity. However, for using core functionalities of SCimilairty like `search_centroids`,  or some of the utils like `align_dataset` or `lognorm_counts` SCimilarity accepts any of the following: pegasusio.MultimodalData, pegasusio.UnimodalData, anndata.AnnData. This is mentioned in detail for each method in the API: https://genentech.github.io/scimilarity/api.html
