### ISSUE TITLE
Cannot use docker to load notebooks

### ISSUE THREAD

**Issue by HelloWorldLTY** [Genentech/scimilarity#5]
Hi, I am using our university hpc. We do not have docker as a module here. Do we have other choices to use the API model? Thanks.

**Comment by HelloWorldLTY** [comment]
Most of the universities will use apptainer, from my understanding:

https://researchcomputing.princeton.edu/support/knowledge-base/singularity
https://docs.ycrc.yale.edu/clusters-at-yale/guides/containers/

Do you have plan to provide a version with apptainer? Thanks.

**Comment by OmarSalem12** [comment]
Hi @HelloWorldLTY, you can always use `pip` to install `SCimilarity` as highlighted in the documentation: https://genentech.github.io/scimilarity/install.html 
You can add --user flag to make sure it install for your user account. 

`git clone https://github.com/genentech/scimilarity.git
cd scimilarity
pip install --user -e .`

Alternatively you can also create a virtual environment for SCimilarity and install it in the environment (you should have full control over the environment). 
I hope this helps

**Comment by javh** [comment]
Greetings @HelloWorldLTY,

In addition to the local install @OmarSalem12  mentioned, if your HPC has Singularity installed (which is common), you can pull the docker container directly as a singularity container and run it through singularity.

See the documentation here on how to pull from the GitHub container registry:
https://apptainer.org/user-docs/master/singularity_and_docker.html#github-container-registry
