### ISSUE TITLE
release of integration model

### ISSUE THREAD

**Issue by YOU-k** [Genentech/scimilarity#7]
Thanks for the nice work and well-documented tutorials.
In the manuscript, you mentioned that there are 2 models used, one is the query model and another is the integration model. I reckon the one that is available to us currently is the query model. what about the integration model? will it be released?
Cheers, Yue

**Comment by gheimberg** [comment]
hi Yue,
Thanks for your interest in SCimilarity! At the moment we don't have plans to release the integration model. While we discuss it in the paper, we actually don't encourage its usage. It makes prettier UMAPs but in other regards we see that it falls short of the query model. In fact, we are re-working the manuscript to reflect this better. 

In the mean time, we are prioritizing clearer documentation, fixes, and more guidelines on how to construct the most informative queries (preventing users from garbage in, garbage out queries). 

We can put the integration model on our to-do list, but at the moment it is not at the top. 

Sorry about the inconvenience!
